### ISSUE TITLE
使用主动扫描运行失败

### ISSUE THREAD

**Issue by Ptkatz** [wrenchonline/glint#10]
PS C:\Users\Administrator\Desktop\glint> .\glint.exe http://testphp.vulnweb.com/
[15:34:35][inf][main.CmdHandler]Enter command mode...
[15:34:35][err][reflect.Value.String]not value
[15:34:35][inf][main.(*Task).dostartTasks]config.EnableCrawler: true
panic: reflect: call of reflect.Value.Int on string Value

goroutine 1 [running]:
reflect.Value.Int(...)
        C:/Program Files/Go/src/reflect/value.go:1459
main.(*Task).dostartTasks(0xc0002cf900, {0x0, 0x1, 0x0, {0x0, 0x0}, {0x0, 0x0}})
        C:/Users/Administrator/Desktop/glint/glint.go:768 +0x1c45
main.CmdHandler(0xc0002a51c0, 0xc0002cf900, {0x0, 0x1, 0x0, {0x0, 0x0}, {0x0, 0x0}})
        C:/Users/Administrator/Desktop/glint/glint.go:1105 +0x345
main.run(0xc0002a51c0)
        C:/Users/Administrator/Desktop/glint/glint.go:311 +0x26b
github.com/urfave/cli/v2.(*App).RunContext(0xc000140700, {0x1916350?, 0xc00002e120}, {0xc0000643c0, 0x2, 0x2})
        E:/GOPATH/pkg/mod/github.com/urfave/cli/v2@v2.16.3/app.go:391 +0xf68
github.com/urfave/cli/v2.(*App).Run(...)
        E:/GOPATH/pkg/mod/github.com/urfave/cli/v2@v2.16.3/app.go:252
main.main()
        C:/Users/Administrator/Desktop/glint/glint.go:263 +0x749

**Comment by wrenchonline** [comment]
{
            "name": "命令行运行",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "${workspaceRoot}",
            "args": [
                "--cert",
                "server.pem",
                "--key",
                "server.key",
                "--config",
                "config.yaml",
                "--configtype",
                "yaml",
                "http://192.168.166.2/pikachu"
            ],
        },
