### ISSUE TITLE
xss 检测似乎会漏报

### ISSUE THREAD

**Issue by sairson** [wrenchonline/glint#11]
http://testphp.vulnweb.com/comment.php?aid=2 提交post类型表单，参数name
![image](https://user-images.githubusercontent.com/74412075/215984345-7438e932-f67a-4a92-b872-e5cfd859b744.png)
glint在解析html语法树的时候，没有解析p标签而直接退出
![image](https://user-images.githubusercontent.com/74412075/215984475-23bdb7e7-5264-4232-9fcc-f2741947a3a1.png)

**Comment by wrenchonline** [comment]
> http://testphp.vulnweb.com/comment.php?aid=2 提交post类型表单，参数name ![image](https://user-images.githubusercontent.com/74412075/215984345-7438e932-f67a-4a92-b872-e5cfd859b744.png) glint在解析html语法树的时候，没有解析p标签而直接退出 ![image](https://user-images.githubusercontent.com/74412075/215984475-23bdb7e7-5264-4232-9fcc-f2741947a3a1.png)
收到，我会尽快的排查。

**Comment by sairson** [comment]
还有一个问题，就是chromedp采用自定义请全头的时候，会出现net::ERR_INVALID_ARGUMENT的问题，这步出自
![image](https://user-images.githubusercontent.com/74412075/215996108-0c963f82-c4e6-43ba-ba37-3daec3756695.png)

**Comment by wrenchonline** [comment]
@sairson 

func Test_ASTParser(t *testing.T) {
	body := `
		<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
	<html>
	<head>
	<title>
	<script>console.log(123)</script> commented</title>
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
	<style type="text/css">
	
	</style>
	<link href="style.css" rel="stylesheet" type="text/css">
	</head>
	<body>
	<p class='story'><script>console.log(123)</script>, thank you for your comment.</p><p class='story'><i></p></i></body>
	</html>
	`
	Location_res := ast.SearchInputInResponse("console.log(123)", body)

	for _, res := range Location_res {
		fmt.Println(res.Details.Value.Tagname)
	}

}

这个貌似能获取到其flag

**Comment by sairson** [comment]
是的，这一步我测验了出来，http://testphp.vulnweb.com/comment.php?aid=2 提交表单和http://testphp.vulnweb.com/comment.php提交表单返回的内容不同，这是我的问题，但是在我替换之后，我依然不能获取到其漏洞报告

**Comment by sairson** [comment]
![image](https://user-images.githubusercontent.com/74412075/215997332-b0d215fc-b263-41b2-9543-696a4c984731.png)
这样的测试用例是错误的吗？

**Comment by wrenchonline** [comment]
> ![image](https://user-images.githubusercontent.com/74412075/215997332-b0d215fc-b263-41b2-9543-696a4c984731.png) 这样的测试用例是错误的吗？

上传了最新的RP

**Comment by sairson** [comment]
好的，谢谢你

**Comment by wrenchonline** [comment]
> 好的，谢谢你

reqmsg抛出有点问题，因为chomedp to http报文 我是临时拼装的。
